[projects]

  [projects.default]
  contents = [
    "about",
    "why_julia",
    "julia_first_encounter",
    "statistics_intro",
    "appendix",
    "references",
  ]

  # Full URL, required for the sitemap and robots.txt.
  online_url = "https://booktemplate.huijzer.xyz"

  # Extra directories to be copied.
  extra_directories = ["images"]

  # Port used by serve()
  port = 8004

  output_filename = "booktemplate"
