name = "RJ_BS_eng"
uuid = "0c3011bc-6234-4894-8ba7-bdcd5fcb1fbb"
authors = ["Bartlomiej Lukaszuk"]
version = "0.1.0"

[deps]
Books = "939d5c6b-51ae-42e7-97ca-7564d0d4ad91"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
Pingouin = "61ac1d4c-5a1f-4019-949c-7919748f8c44"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
